### ISSUE TITLE
我十分的希望能在下一次的更新中看到来着Arcaea中的Tempestissimo这首曲子，感谢作者！！！

### ISSUE THREAD

**Issue by Zhouttt** [luern0313/WindSong-Lyre-Genshin-Impact#1]
[tempestissimo.zip](https://github.com/luern0313/WindSong-Lyre-Genshin-Impact/files/6226147/tempestissimo.zip)
这是Tempestissimo的MIDI文件

**Comment by luern0313** [comment]
会看看的

**Comment by wszbzb** [comment]
希望会有there is a reason

**Comment by luern0313** [comment]
> [tempestissimo.zip](https://github.com/luern0313/WindSong-Lyre-Genshin-Impact/files/6226147/tempestissimo.zip)
> 这是Tempestissimo的MIDI文件

已经加上了
