### ISSUE TITLE
听书人mid，这个应该怎么调教啊？

### ISSUE THREAD

**Issue by hiarno** [luern0313/WindSong-Lyre-Genshin-Impact#16]
[【原神】「钟离：听书人」.mid.zip](https://github.com/luern0313/WindSong-Lyre-Genshin-Impact/files/6781873/mid.zip)
听书人mid，这个应该怎么调教啊？

**Comment by hiarno** [comment]
大佬，在不在？

**Comment by luern0313** [comment]
要把多余的轨道去掉，最多留个主旋律和和弦，还有要移调，还有要尽量保持音高跨度在三个八度以内，把和弦的低音往上升一两个八度
