### ISSUE TITLE
想请教mid文件如何入门调教（校

### ISSUE THREAD

**Issue by Zacky-ran** [luern0313/WindSong-Lyre-Genshin-Impact#3]
//作者大大能不能加两首八爷的歌，lemon、灰色与青啥的...
刚才试着自己找了下《lemon》的mid文件，读入的时候mido库报错“data byte must be in range 0,127”，能找到的资料比较少，在尝试clip=True后能正常读入，但是演奏的效果不如预期。本人音痴，猜想是调子或者音阶(?)什么的不对，是这样吗？另外想请教下如何快速入门mid文件呢，想自己扩展下曲目。
谢谢作者

**Comment by luern0313** [comment]
需要一个编曲软件比如fl，把多余的轨道去掉，留个主旋律和和弦，要移调，然后尽量保持音高跨度在三个八度以内，把和弦的低音往上升一两个八度

**Comment by Zacky-ran** [comment]
所以，我理解的是，必须要乐理知识先简单入门吗（

**Comment by luern0313** [comment]
我感觉需要一些乐理。。毕竟移调什么的只能靠听判断移多少了

**Comment by Zacky-ran** [comment]
..好吧
