### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by mr258876** [luern0313/WindSong-Lyre-Genshin-Impact#6]
作者大大好！首先感谢大佬的代码，之前也想用python做这个只是最后按键没能实现😂，今天看到这个项目以后感觉获益匪浅。
在使用过程中我发现有几个地方可以改进：
1.可以在开始弹奏之前加一个倒计时方便切窗口
2.在部分多音轨的midi谱中存在多个音轨同时演奏一个音的情况，可能会导致同一个键被重复按下，在演奏之前遍历一边midi文件并把重复的音删掉应该可以解决这个问题
目前就发现这两个

**Comment by luern0313** [comment]
1正在做
2的话。。重复按下不影响演奏的吧，如果两个音开始时间相同的话

**Comment by luern0313** [comment]
如果两个音不同时开始，只是时间有重合不影响的，原神这个琴是只看按下的时间再加个延时而已

**Comment by mr258876** [comment]
感谢解答！
顺便问下能不能把这首歌放进去？
[Doki Doki Literature Club!.zip](https://github.com/luern0313/WindSong-Lyre-Genshin-Impact/files/6244735/Doki.Doki.Literature.Club.zip)

**Comment by luern0313** [comment]
这个应该可以直接用吧

**Comment by luern0313** [comment]
加上去了
